version: "3"
services:
  back:
    container_name: strava-back
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: strava-db
    image: mongo
    ports:
      - "27017:27017"
